const serie=[
{   
    imgSrc: require('../components/Images/Series/TheATeam.png'),
    titreSeries:'The A-Team',
    diffusion:'1983-1987',
    actprincSerie: [
        'George Peppard',
        'Dirk Benedict',
        'Dwight Schultz',
        'Mister T',
    ],
    resumSerie: "Pendant la guerre du Viêt Nam, le chef hiérarchique de l'Agence tous risques, le général Morrison, leur a donné l'ordre de voler la banque de Hanoï afin de précipiter la fin de la guerre. La mission est un succès, mais quatre jours après la fin de la guerre, ils retrouvent le général assassiné par les Viet Cong, le quartier général étant entièrement brûlé. Par conséquent, aucune preuve indiquant que l'Agence tous risques agissait sur ordre n'existe. Les membres passent alors devant une cour de justice militaire, celle-ci les condamnant à la prison. Incarcérés aux États-Unis, ils s'évadent rapidement et mènent désormais une vie de mercenaires au service « de la veuve et de l'orphelin », combattant les injustices locales.",
    genreSerie: 'Action',
    natioSerie: 'Américain',
    saisons:'1',
    episode:'99',
    dureeSerie: '60min'
},
{   imgSrc: require('../components/Images/Series/MacGyver.png'),
    titreSeries: "MacGyver",
    diffusion: "1985-1992",
    actprincSerie: [
        "Richard Dean Anderson",
        "Dana Elcar",
    ],
    resumSerie: "Angus MacGyver est un agent secret immatriculé DXSID N°XC4479 au département des services externes, puis employé de la Fondation Phoenix, une société privée à but non lucratif. À partir de l'épisode 11, son chef de service, qui est aussi son ami, est Peter Thornton. C'est d'ailleurs lui qui va lui proposer d'entrer à la Fondation Phoenix par la suite.",
    genreSerie:[ 
        "Action",
        "Aventure",
        "Espionnage",
                ],
    natioSerie: "Américain",
    saisons:"7",
    episode:"139",
    dureeSerie: "47min"     
},
{   
    imgSrc: require('../components/Images/Series/GameOfThrones.png'),
    titreSeries: "Game of Thrones",
        diffusion: "2011-en production",
        actprincSerie: [
            "Kit Haringtonn",
            "Peter Dinklage",
            "Emilia Clarke",
            "Sophie Turner",
            "Lena Headey",
            "Maisie Williams",
            "Nikolaj Coster-Waldau",
            "John Bradley-West",
        ],
        resumSerie: "Sur le continent de Westeros, le roi Robert Baratheon gouverne le Royaume des Sept Couronnes depuis plus de dix-sept ans, à la suite de la rébellion qu'il a menée contre le « roi fou » Aerys II Targaryen. Jon Arryn, époux de la sœur de Lady Catelyn Stark, Lady Arryn, son guide et principal conseiller, vient de décéder, et le roi part alors dans le nord du royaume demander à son vieil ami Eddard « Ned » Stark de remplacer leur regretté mentor au poste de Main du roi. Ned, seigneur suzerain du nord depuis Winterfell et de la maison Stark, est peu désireux de quitter ses terres. Mais il accepte à contre-cœur de partir pour la capitale Port-Réal avec ses deux filles, Sansa et Arya. Juste avant leur départ pour le sud, Bran, l'un des jeunes fils d'Eddard, est poussé de l'une des tours de Winterfell après avoir été témoin de la liaison incestueuse entre la reine Cersei Baratheon et son frère jumeau, Jaime Lannister. Leur frère, Tyrion Lannister, surnommé « le gnome », est alors accusé du crime par Lady Catelyn Stark.",
        genreSerie:[ 
            "Fantasy médiévale",
            "Drame",
                    ],
        natioSerie: "Américain",
        saisons:"7",
        episode:"67",
        dureeSerie: "47 à 79 minutes"
},
{   
    imgSrc: require('../components/Images/Series/TheWalkingDead.png'),
    titreSeries: "The Walking Dead",
    diffusion: "2010 – en production",
    actprincSerie: [
        "Andrew Lincoln",
        "Norman Reedus",
        "Steven Yeun",
        "Melissa McBride",
        "Chandler Riggs",
        "Lauren Cohan",
        "Danai Gurira",
        "Alanna Masterson",
        "Josh McDermitt",
        "Christian Serratos",
        "Jeffrey Dean Morgan",
    ],
    resumSerie: "L'histoire suit le personnage de Rick Grimes (interprété par Andrew Lincoln), adjoint du shérif du comté de Kings (en Géorgie) qui se réveille d'un coma de plusieurs semaines pour découvrir que la population a été ravagée par une épidémie post-apocalyptique inconnue qui transforme les êtres humains en morts-vivants, appelés « rôdeurs ». Après avoir retrouvé sa famille, il devient très vite le leader d'un groupe de rescapés d'Atlanta. Ils seront amenés à devoir survivre dans un monde post-apocalyptique face à des rôdeurs et d'autres groupes de survivants, pour certains plus dangereux encore que les rôdeurs eux-mêmes. Ensemble, ils vont devoir tant bien que mal faire face à ce nouveau monde devenu méconnaissable, à travers leur périple dans le Sud profond des États-Unis.",
    genreSerie:
        "horreur",
    natioSerie: "Américain",
    saisons:"9",
    episode:"	129 + 13 webisodes",
    dureeSerie:[ "	7 × 62 - 68 minutes"
                    ,"8 × 50 - 60 minutes",
                    "94 x 42 - 45 minutes"]

},
{   
    imgSrc: require('../components/Images/Series/ThisIsUs.png'),
    titreSeries: "This Is Us",
    diffusion: "2016 – en production",
    actprincSerie: [
            "Mandy Moore",
            "Milo Ventimiglia",
            "Sterling K. Brown",
            "Justin Hartley",
            "Chrissy Metz",
            "Susan Kelechi Watson",
            "Chris Sullivan",
        ],
        resumSerie: "La série suit la vie de frères et sœurs Kevin, Kate et Randall (connus sous le nom de « Big Three »), ainsi que de leurs parents, Jack et Rebecca Pearson. L'action se déroule en 2016-2018 et utilise des flashbacks pour montrer la famille à divers moments du passé. Kevin et Kate sont les deux membres survivants d'une grossesse triplée, née six semaines avant terme le jour du 36e anniversaire de Jack en 1980 ; leur frère est mort-né. Estimant qu'ils devaient avoir trois enfants, Jack et Rebecca, ont décidé d'adopter dans leur famille blanche, Randall, un enfant afro-américain né le même jour et amené au même hôpital après l'abandon de son père biologique dans une caserne de pompiers. Jack meurt quand ses enfants ont 17 ans.",
        genreSerie:
            "Comédie dramatique",
        natioSerie: "Américain",
        saisons:"3",
        episode:"50",
        dureeSerie:"42minutes"
},
{   
    imgSrc: require('../components/Images/Series/Booker.png'),
    titreSeries: "Booker",
    diffusion: "2089 – 1990",
    actprincSerie: [
            "Richard Grieco ",
            "Katie Rich",
            "Carmen Argenziano",
            "Marcia Strassman ",
            "Lori Petty",
        ],
    resumSerie: "Après avoir perdu son emploi de policier à Los Angeles, Dennis Booker est devenu enquêteur pour une compagnie d'assurances japonaise, la Teshima Corporation of America.",
    genreSerie:
            "policière",
    natioSerie: "Américain",
        saisons:"	1",
        episode:"22",
        dureeSerie:"45minutes",
},
{   
    imgSrc: require('../components/Images/Series/Stingray.png'),
    titreSeries: "Stingray",
    diffusion: "2064 – 1965",
    actprincSerie: [
            "Don Mason",
            "Robert Easton",
            "Ray Barrett",
            "Lois Maxwell ",
            "David Graham",
            "Gary Miller",
        ],
    resumSerie: "En 2065, la patrouille de sécurité aquatique mondiale (World Aquanaut Security Patrol - WASP) combat les Aquaphibiens, une race de guerriers sous-marins dirigée par le roi Titan, désireux d'exterminer les terriens afin de prendre possession de la Terre. Le capitaine Troy Tempest est à la tête de l'escadrille sous-marine et son arme ultime, le Stingray, un sous-marin atomique équipé des dernières technologies.",
    genreSerie:[ " marionnettes",
            "Science-fiction",
        ],
    natioSerie: "Américain",
    saisons:"	1",
    episode:"39",
    dureeSerie:"25minutes"
},
{   
    imgSrc: require('../components/Images/Series/AlerteCobra.png'),
    titreSeries: "Alerte Cobra",
    diffusion: "1996 – En production",
    actprincSerie: [
            "Erdogan Atalay",
            "Daniel Roesner",
            "Katrin Heß",
            "Daniela Wutte ",
            "Katja Woywood",
            "Carina Wiese",
            "Niels Kurvin",
        ],
    resumSerie: "Sami Gerçan et son équipe (l'équipe « Cobra 11 ») font face à de nombreux criminels. Leurs enquêtes se finissent régulièrement par des poursuites et des explosions spectaculaires qui se déroulent toujours dans des conditions extrêmes sur l'autoroute, ou en ville.",
        "genreSerie":[ " policier",
            "Action",
        ],
    natioSerie: "Allemand",
    saisons:"	45",
    episode:"349",
    dureeSerie:"45minutes"
},
{   
    imgSrc: require('../components/Images/Series/caprica.png'),
    titreSeries: "Caprica",
    diffusion: "2010 – 2010",
    actprincSerie: [
            "Eric Stoltz",
            "Esai Morales",
            "Paula Malcomson",
            "Alessandra Torresani",
            "Magda Apanowicz",
        ],
        resumSerie: "Caprica s'est délibérément écartée de la série dont elle était dérivée pour des impératifs artistiques et commerciaux3. Ronald D. Moore défendit résolument cette décision en expliquant qu'il ne s'agissait pas d'appliquer une recette (« …you don't try to repeat the formula »)4. De plus, si Battlestar Galactica avait été un succès critique, la série n'avait touché qu'un public principalement masculin et la chaîne de télévision était convaincue que le contexte de la guerre spatiale rebutait le public féminin5. Pour ces raisons et parce que la version initiale de Caprica mettait en scène des événements précédant les guerres cylons, la série possède une personnalité qui lui est propre et a su trouver son ton, son contenu et son style. Caprica contient des éléments qui éclairent sans doute la compréhension de la série originale, mais se veut accessible à un public qui n'aurait jamais vu Battlestar Galactica6",
        genreSerie:" science-fiction",
        natioSerie: "Américain",
        saisons:"1",
        episode:"18",
        dureeSerie:"42minutes", 
},
{   
    imgSrc: require('../components/Images/Series/TheExpanse.png'),
    titreSeries: "The Expanse",
    diffusion: "2015 – 2018",
        actprincSerie: [
            "Thomas Jane",
            "Steven Strait",
            "Shohreh Aghdashloo",
            "Dominique Tipper",
            "Cas Anvar",
            "Wes Chatham",
        ],
        resumSerie: "200 ans dans le futur, le système solaire est entièrement colonisé. Le détective Josephus Miller, né sur la Station Cérès dans la ceinture d'astéroïdes, a pour mission de retrouver une jeune femme, Julie Mao. Il est bientôt épaulé dans sa tâche par James Holden, second du cargo spatial impliqué dans un incident qui va exacerber les relations tendues entre une Terre dirigée par les Nations unies appauvrie en ressource, la République du Congrès martien, prospère et de plus en plus puissante, et les colonies de la ceinture d'astéroïdes, dirigées par la Terre et Mars et dont les natifs sont surexploités. Ils vont bientôt découvrir que la disparition de la jeune femme est liée à une vaste conspiration qui menace la paix dans le système solaire et la survie de l'humanité.",
        genreSerie:" Science-fiction",
        natioSerie: "Américain",
        saisons:"3",
        episode:"36",
        dureeSerie:"45minutes",
},
{   
    imgSrc: require('../components/Images/Series/PrettyLittleLiars.png'),
    titreSeries: "Pretty Little Liars",
    diffusion: "2010 – 2017",
    actprincSerie: [
        "Troian Bellisario",
        "Ashley Benson",
        "Lucy Hale",
        "Shay Mitchell",
        "Ian Harding",
        "Laura Leighton",
        "Sasha Pieterse",
    ],
    resumSerie: "Un soir dans la petite ville de Rosewood, un groupe de cinq meilleures amies se réunit pour une soirée pyjama avant la rentrée. Le groupe est composé de Spencer Hastings, Hanna Marin, Aria Montgomery, Emily Fields et de leur leader, Alison DiLaurentis. Mais dans la nuit, Alison disparaît sans laisser de traces.Un an plus tard, Alison est toujours portée disparue et le groupe est séparé. Mais quand Aria fait son retour en ville après avoir passé l'année à l'étranger avec ses parents, chacune commence à recevoir des messages et des menaces signés « -A ». Ce dernier connaît les nombreux secrets des jeunes filles, plusieurs dont seule Alison connaissait l'existence mais également certains nés après la disparition de l'adolescente. Mais « -A » semble également en savoir beaucoup sur la disparition d'Alison.",
    genreSerie:[
        "thriller ",
        "dramatique ",             
],
    natioSerie: "Américain",
    saisons:"7",
    episode:"160",
    dureeSerie:"39 à 44 minutes"
}
]
export{serie}
/*
//imgSrc: require('C:\Users\campus\ProjetMovies\imgSeries\The A-Team.jpg'),


export const SeriesDataList=  [
    {
        "idSeries": 1,
        "title": "The A-Team",
        "periode de diffusion": "1983-1987",
        "actprincSerie": [
            "George Peppard",
            "Dirk Benedict",
            "Dwight Schultz",
            "Mister T",
        ],
        "resumSerie": "Pendant la guerre du Viêt Nam, le chef hiérarchique de l'Agence tous risques, le général Morrison, leur a donné l'ordre de voler la banque de Hanoï afin de précipiter la fin de la guerre. La mission est un succès, mais quatre jours après la fin de la guerre, ils retrouvent le général assassiné par les Viet Cong, le quartier général étant entièrement brûlé. Par conséquent, aucune preuve indiquant que l'Agence tous risques agissait sur ordre n'existe. Les membres passent alors devant une cour de justice militaire, celle-ci les condamnant à la prison. Incarcérés aux États-Unis, ils s'évadent rapidement et mènent désormais une vie de mercenaires au service « de la veuve et de l'orphelin », combattant les injustices locales.",
        "genreSerie": "Action",
        "natioSerie": "Américain",
        "saisons":"1",
        "episode":"1",
        "dureeSerie": "60min",
        "videoSerie": "https://www.youtube.com/watch?v=kdkA0lLc_X4",
        "imgSerie": "C:\Users\campus\ProjetMovies\imgSeries\the_a_team.jpg"
    },
    {
        "idSeries": 2,
        "titreSeries": "MacGyver",
        "periode de diffusion": "1985-1992",
        "actprincSerie": [
            "Richard Dean Anderson",
            "Dana Elcar",
        ],
        "resumSerie": "Angus MacGyver est un agent secret immatriculé DXSID N°XC4479 au département des services externes, puis employé de la Fondation Phoenix, une société privée à but non lucratif. À partir de l'épisode 11, son chef de service, qui est aussi son ami, est Peter Thornton. C'est d'ailleurs lui qui va lui proposer d'entrer à la Fondation Phoenix par la suite.",
        "genreSerie":[ 
            "Action",
            "Aventure",
            "Espionnage",
                    ],
        "natioSerie": "Américain",
        "saisons":"7",
        "episode":"1",
        "dureeSerie": "47min",
        "videoSerie": "https://www.youtube.com/watch?v=87dGAlJE0cQ",
        "imgSerie": "C:\Users\campus\ProjetMovies\imgSeries\MacGyver.jpg"
    },
    {
        "idSeries": 3,
        "titreSeries": "Game of Thrones",
        "periode de diffusion": "2011-en production",
        "actprincSerie": [
            "Kit Haringtonn",
            "Peter Dinklage",
            "Emilia Clarke",
            "Sophie Turner",
            "Lena Headey",
            "Maisie Williams",
            "Nikolaj Coster-Waldau",
            "John Bradley-West",
        ],
        "resumSerie": "Sur le continent de Westeros, le roi Robert Baratheon gouverne le Royaume des Sept Couronnes depuis plus de dix-sept ans, à la suite de la rébellion qu'il a menée contre le « roi fou » Aerys II Targaryen. Jon Arryn, époux de la sœur de Lady Catelyn Stark, Lady Arryn, son guide et principal conseiller, vient de décéder, et le roi part alors dans le nord du royaume demander à son vieil ami Eddard « Ned » Stark de remplacer leur regretté mentor au poste de Main du roi. Ned, seigneur suzerain du nord depuis Winterfell et de la maison Stark, est peu désireux de quitter ses terres. Mais il accepte à contre-cœur de partir pour la capitale Port-Réal avec ses deux filles, Sansa et Arya. Juste avant leur départ pour le sud, Bran, l'un des jeunes fils d'Eddard, est poussé de l'une des tours de Winterfell après avoir été témoin de la liaison incestueuse entre la reine Cersei Baratheon et son frère jumeau, Jaime Lannister. Leur frère, Tyrion Lannister, surnommé « le gnome », est alors accusé du crime par Lady Catelyn Stark.",
        "genreSerie":[ 
            "Fantasy médiévale",
            "Drame",
                    ],
        "natioSerie": "Américain",
        "saisons":"7",
        "episode":"67",
        "dureeSerie": "47 à 79 minutes",
        "videoSerie": "https://www.youtube.com/watch?v=87dGAlJE0cQ",
        "imgSerie": "C:\Users\campus\ProjetMovies\imgSeries\Game of Thrones.jpg"
    },
    {
        "idSeries": 4,
        "titreSeries": "The Walking Dead",
        "periode de diffusion": "2010 – en production",
        "actprincSerie": [
            "Andrew Lincoln",
            "Norman Reedus",
            "Steven Yeun",
            "Melissa McBride",
            "Chandler Riggs",
            "Lauren Cohan",
            "Danai Gurira",
            "Alanna Masterson",
            "Josh McDermitt",
            "Christian Serratos",
            "Jeffrey Dean Morgan",
        ],
        "resumSerie": "L'histoire suit le personnage de Rick Grimes (interprété par Andrew Lincoln), adjoint du shérif du comté de Kings (en Géorgie) qui se réveille d'un coma de plusieurs semaines pour découvrir que la population a été ravagée par une épidémie post-apocalyptique inconnue qui transforme les êtres humains en morts-vivants, appelés « rôdeurs ». Après avoir retrouvé sa famille, il devient très vite le leader d'un groupe de rescapés d'Atlanta. Ils seront amenés à devoir survivre dans un monde post-apocalyptique face à des rôdeurs et d'autres groupes de survivants, pour certains plus dangereux encore que les rôdeurs eux-mêmes. Ensemble, ils vont devoir tant bien que mal faire face à ce nouveau monde devenu méconnaissable, à travers leur périple dans le Sud profond des États-Unis.",
        "genreSerie":
            "horreur",
        "natioSerie": "Américain",
        "saisons":"9",
        "episode":"	129 + 13 webisodes",
        "dureeSerie":[ "	7 × 62 - 68 minutes","8 × 50 - 60 minutes","94 x 42 - 45 minutes"],
        "videoSerie": "https://www.youtube.com/watch?v=-wPuWTmE7gA",
        "imgSerie": "C:\Users\campus\ProjetMovies\imgSeries\The Walking Dead.jpg"
    },
    {
        "idSeries": 5,
        "titreSeries": "This Is Us",
        "periode de diffusion": "2016 – en production",
        "actprincSerie": [
            "Mandy Moore",
            "Milo Ventimiglia",
            "Sterling K. Brown",
            "Justin Hartley",
            "Chrissy Metz",
            "Susan Kelechi Watson",
            "Chris Sullivan",
        ],
        "resumSerie": "La série suit la vie de frères et sœurs Kevin, Kate et Randall (connus sous le nom de « Big Three »), ainsi que de leurs parents, Jack et Rebecca Pearson. L'action se déroule en 2016-2018 et utilise des flashbacks pour montrer la famille à divers moments du passé. Kevin et Kate sont les deux membres survivants d'une grossesse triplée, née six semaines avant terme le jour du 36e anniversaire de Jack en 1980 ; leur frère est mort-né. Estimant qu'ils devaient avoir trois enfants, Jack et Rebecca, ont décidé d'adopter dans leur famille blanche, Randall, un enfant afro-américain né le même jour et amené au même hôpital après l'abandon de son père biologique dans une caserne de pompiers. Jack meurt quand ses enfants ont 17 ans.",
        "genreSerie":
            "Comédie dramatique",
        "natioSerie": "Américain",
        "saisons":"	3",
        "episode":"50",
        "dureeSerie":"42minutes",
        "videoSerie": "https://www.youtube.com/watch?v=hljQfJLQmaI",
        "imgSerie": "C:\Users\campus\ProjetMovies\imgSeries\this is us.jpg"
    },
    {
        "idSeries": 6,
        "titreSeries": "Booker",
        "periode de diffusion": "2089 – 1990",
        "actprincSerie": [
            "Richard Grieco ",
            "Katie Rich",
            "Carmen Argenziano",
            "Marcia Strassman ",
            "Lori Petty",
        ],
        "resumSerie": "Après avoir perdu son emploi de policier à Los Angeles, Dennis Booker est devenu enquêteur pour une compagnie d'assurances japonaise, la Teshima Corporation of America.",
        "genreSerie":
            "policière",
        "natioSerie": "Américain",
        "saisons":"	1",
        "episode":"22",
        "dureeSerie":"45minutes",
        "videoSerie": "https://www.youtube.com/watch?v=tH4ySG-KLm8",
        "imgSerie": "C:\Users\campus\ProjetMovies\imgSeries\Booker.jpg"
    },
    {
        "idSeries": 7,
        "titreSeries": "Stingray",
        "periode de diffusion": "2064 – 1965",
        "actprincSerie": [
            "Don Mason",
            "Robert Easton",
            "Ray Barrett",
            "Lois Maxwell ",
            "David Graham",
            "Gary Miller",
        ],
        "resumSerie": "En 2065, la patrouille de sécurité aquatique mondiale (World Aquanaut Security Patrol - WASP) combat les Aquaphibiens, une race de guerriers sous-marins dirigée par le roi Titan, désireux d'exterminer les terriens afin de prendre possession de la Terre. Le capitaine Troy Tempest est à la tête de l'escadrille sous-marine et son arme ultime, le Stingray, un sous-marin atomique équipé des dernières technologies.",
        "genreSerie":[ " marionnettes",
            "Science-fiction",
        ],
        "natioSerie": "Américain",
        "saisons":"	1",
        "episode":"39",
        "dureeSerie":"25minutes",
        "videoSerie": "https://www.youtube.com/watch?v=tH4ySG-KLm8",
        "imgSerie": "C:\Users\campus\ProjetMovies\imgSeries\Stingray.jpg"
    },
    {
        "idSeries": 8,
        "titreSeries": "Alerte Cobra",
        "periode de diffusion": "1996 – En production",
        "actprincSerie": [
            "Erdogan Atalay",
            "Daniel Roesner",
            "Katrin Heß",
            "Daniela Wutte ",
            "Katja Woywood",
            "Carina Wiese",
            "Niels Kurvin",
        ],
        "resumSerie": "Sami Gerçan et son équipe (l'équipe « Cobra 11 ») font face à de nombreux criminels. Leurs enquêtes se finissent régulièrement par des poursuites et des explosions spectaculaires qui se déroulent toujours dans des conditions extrêmes sur l'autoroute, ou en ville.",
        "genreSerie":[ " policier",
            "Action",
        ],
        "natioSerie": "Allemand",
        "saisons":"	45",
        "episode":"349",
        "dureeSerie":"45minutes",
        "videoSerie": "https://www.youtube.com/watch?v=vjBd8BArRdQ",
        "imgSerie": "C:\Users\campus\ProjetMovies\imgSeries\Alerte Cobra.jpg"
    },
    {
        "idSeries": 9,
        "titreSeries": "Caprica",
        "periode de diffusion": "2010 – 2010",
        "actprincSerie": [
            "Eric Stoltz",
            "Esai Morales",
            "Paula Malcomson",
            "Alessandra Torresani",
            "Magda Apanowicz",
        ],
        "resumSerie": "Caprica s'est délibérément écartée de la série dont elle était dérivée pour des impératifs artistiques et commerciaux3. Ronald D. Moore défendit résolument cette décision en expliquant qu'il ne s'agissait pas d'appliquer une recette (« …you don't try to repeat the formula »)4. De plus, si Battlestar Galactica avait été un succès critique, la série n'avait touché qu'un public principalement masculin et la chaîne de télévision était convaincue que le contexte de la guerre spatiale rebutait le public féminin5. Pour ces raisons et parce que la version initiale de Caprica mettait en scène des événements précédant les guerres cylons, la série possède une personnalité qui lui est propre et a su trouver son ton, son contenu et son style. Caprica contient des éléments qui éclairent sans doute la compréhension de la série originale, mais se veut accessible à un public qui n'aurait jamais vu Battlestar Galactica6",
        "genreSerie":" science-fiction",
        "natioSerie": "Américain",
        "saisons":"1",
        "episode":"18",
        "dureeSerie":"42minutes",
        "videoSerie": "https://www.youtube.com/watch?v=d2D32c_Zi5Y",
        "imgSerie": "C:\Users\campus\ProjetMovies\imgSeries\caprica.jpg"
    },
    {
        "idSeries": 10,
        "titreSeries": "The Expanse",
        "periode de diffusion": "2015 – 2018",
        "actprincSerie": [
            "Thomas Jane",
            "Steven Strait",
            "Shohreh Aghdashloo",
            "Dominique Tipper",
            "Cas Anvar",
            "Wes Chatham",
        ],
        "resumSerie": "200 ans dans le futur, le système solaire est entièrement colonisé. Le détective Josephus Miller, né sur la Station Cérès dans la ceinture d'astéroïdes, a pour mission de retrouver une jeune femme, Julie Mao. Il est bientôt épaulé dans sa tâche par James Holden, second du cargo spatial impliqué dans un incident qui va exacerber les relations tendues entre une Terre dirigée par les Nations unies appauvrie en ressource, la République du Congrès martien, prospère et de plus en plus puissante, et les colonies de la ceinture d'astéroïdes, dirigées par la Terre et Mars et dont les natifs sont surexploités. Ils vont bientôt découvrir que la disparition de la jeune femme est liée à une vaste conspiration qui menace la paix dans le système solaire et la survie de l'humanité.",
        "genreSerie":" Science-fiction",
        "natioSerie": "Américain",
        "saisons":"3",
        "episode":"36",
        "dureeSerie":"45minutes",
        "videoSerie": "https://www.youtube.com/watch?v=5eKUvQGdgo0",
        "imgSerie": "C:\Users\campus\ProjetMovies\imgSeries\The Expanse.jpg"
    },
    {
        "idSeries": 11,
        "titreSeries": "Pretty Little Liars",
        "periode de diffusion": "2010 – 2017",
        "actprincSerie": [
            "Troian Bellisario",
            "Ashley Benson",
            "Lucy Hale",
            "Shay Mitchell",
            "Ian Harding",
            "Laura Leighton",
            "Sasha Pieterse",
        ],
        "resumSerie": "Un soir dans la petite ville de Rosewood, un groupe de cinq meilleures amies se réunit pour une soirée pyjama avant la rentrée. Le groupe est composé de Spencer Hastings, Hanna Marin, Aria Montgomery, Emily Fields et de leur leader, Alison DiLaurentis. Mais dans la nuit, Alison disparaît sans laisser de traces.Un an plus tard, Alison est toujours portée disparue et le groupe est séparé. Mais quand Aria fait son retour en ville après avoir passé l'année à l'étranger avec ses parents, chacune commence à recevoir des messages et des menaces signés « -A ». Ce dernier connaît les nombreux secrets des jeunes filles, plusieurs dont seule Alison connaissait l'existence mais également certains nés après la disparition de l'adolescente. Mais « -A » semble également en savoir beaucoup sur la disparition d'Alison.",
        "genreSerie":[
            "thriller ",
            "dramatique ",             
    ],
        "natioSerie": "Américain",
        "saisons":"7",
        "episode":"160",
        "dureeSerie":"39 à 44 minutes",
        "videoSerie": "https://www.youtube.com/watch?v=mgdHbEM9UzI",
        "imgSerie": "C:\Users\campus\ProjetMovies\imgSeries\Pretty Little Liars.jpg"
    },
]*/