/*const books = [
    
    {imgSrc: require('imageLivre/png/ApprentiAssassin.png'),title:'L apprenti assassin',date:'1998'},
    {imgSrc: require('imageLivre/png/AuBonheurDesDames.png'),title:'AU BONHEUR DES DAMES',date:'1883'},
    {imgSrc: require('imageLivre/png/CercleBleuMartarese.png'),title:'LE CERCLE BLEU DES MARTARESE',date:'1979'},
    {imgSrc: require('imageLivre/png/CommunauteAnneau.png'),title:'LE SEIGNEUR DES ANNEAUX',date:'1972'},
    {imgSrc: require('imageLivre/png/EpeeShannara.png'),title:'L EPEE DE SHANNARA',date:'2002'},
    {imgSrc: require('imageLivre/png/HarryPotter.png'),title:'HARRY POTTER A L ECOLE DES SORCIERS',date:'1998'},
    {imgSrc: require('imageLivre/png/LaBeteHumaine.png'),title:'LA BETE HUMAINE',date:'1889'},
    {imgSrc: require('imageLivre/png/LaMemoireDansLaPeau.png'),title:'La mémoire dans la peau',date:'1981'},
    {imgSrc: require('imageLivre/png/LaNuitDesTemps.png'),title:'La nuit des temps',date:'1968'},
    {imgSrc: require('imageLivre/png/LEpreuve.png'),title:'LE LABYRINTHE',date:'2012'},
    {imgSrc: require('imageLivre/png/RendezVousRama.png'),title:'rendez-vous avec Rama',date:'1975'}
    
]
export {books}*/

const books =[
    {imgSrc: require('../components/Images/Livres/ApprentiAssassin.png'),
    title:'L’apprenti assassin',
    date:'1998',
    serieLivre:'L’assassin royal',
     genreLivre:'Fantasy',
      auteurLivre:'Robin Hobb',
       nombrePageLivre:'416',
        editeurLivre:'Pygmalion',
         isbnLivre:'2857045603',
          resumeLivre:'\nCe premier livre raconte les débuts de Fitz (son vrai nom étant FitzChevalerie, hérité de son père, Chevalerie) comme bâtard, au château de Castelcerf où il commence son entraînement d’assassin, et se termine par sa première mission qu’il finira au péril de sa vie.\nL’histoire débute avec Fitz (jusque-là appelé « Petit »), déposé par son modeste grand-père au château d’Œil-de-Lune, puis présenté au prince Vérité, sa famille ne pouvant l’entretenir à cause de ses moyens limités. Malgré son très jeune âge, Fitz montre des dispositions dans une ancienne magie obscure appelée le Vif, qui lui permet de communiquer par télépathie avec un chien nommé Fouinot. Vérité décide d’emmener Fitz au château de Castelcerf... '},
    {imgSrc: require('../components/Images/Livres/AuBonheurDesDames.png'),
    title:'AU BONHEUR DES DAMES',
    date:'1883',
     serieLivre:'Les Rougon-Macquart',
      genreLivre:'Roman naturaliste',
       auteurLivre:'Émile Zola',
        nombrePageLivre:'542',
         editeurLivre:'G. Charpentier',
          isbnLivre:' - ',
           resumeLivre:'\nOctave Mouret affole les femmes de désir. Son grand magasin parisien, Au Bonheur des Dames, est un paradis pour les sens. Les tissus s’amoncellent, éblouissants, délicats, de faille ou de soie. Tout ce qu’une femme peut acheter en 1883, Octave Mouret le vend, avec des techniques révolutionnaires. Le succès est immense. Mais ce bazar est une catastrophe pour le quartier, les petits commerces meurent, les spéculations immobilières se multiplient. Et le personnel connaît une vie d’enfer. Denise échoue de Valognes dans cette fournaise, démunie mais tenace. Zola fait de la jeune fille et de son puissant patron amoureux d’elle le symbole du modernisme et des crises qu’il suscite...'},
    {imgSrc: require('../components/Images/Livres/CercleBleuMartarese.png'),
    title:'LE CERCLE BLEU DES MARTARESE',
    date:'1979', serieLivre:' - ',
     genreLivre:'Espionnage',
      auteurLivre:'Robert Ludlum',
       nombrePageLivre:'704',
        editeurLivre:'Le Livre de Poche',
         isbnLivre:'225306582X',
          resumeLivre:'\nLe Cercle bleu des Matarèse, c’est l’histoire de deux hommes, agents secrets exceptionnels. L’un est américain, Brandon Scofield, l’autre soviétique, Vasili Taleniekov. Ces deux vrais professionnels sont aussi des ennemis mortels car chacun a le cadavre d’un être aimé à reprocher à l’autre. Ils sont maintenant à la fin de leur carrière.\nMais Taleniekov a découvert un complot effrayant une organisation, les Matarèse, qui finance des groupes terroristes. Personne ne connaît vraiment leur but, mais il faut les arrêter. Et les seuls qui en soient capables sont Brandon Scofield et Vasili Taleniekov, travaillant en équipe. Une course folle s’engage, qui nous conduira de la Corse à Boston, en passant par Leningrad, Londres et Rome...'},
    {imgSrc: require('../components/Images/Livres/CommunauteAnneau.png'),
    title:'LA COMMUNAUTE DE L’ANNEAU',
    date:'1972',
     serieLivre:'LE SEIGNEUR DES ANNEAUX',
      genreLivre:'Fantasy',
       auteurLivre:'J. R. R. Tolkien',
        nombrePageLivre:'687',
         editeurLivre:'Christian Bourgois Éditeur',
          isbnLivre:' - ',
           resumeLivre:'\nAux temps reculés qu’évoque le récit, la Terre est peuplée d’innombrables créatures étranges. Les Hobbits, apparentés à l’Homme, mais proches également des Elfes et des Nains, vivent en paix au nord-ouest de l’Ancien Monde, dans la Comté. Paix précaire et menacée, cependant, depuis que Bilbon Sacquet a dérobé au monstre Gollum l’anneau de Puissance jadis forgé par Sauron de Mordor. Car cet anneau est doté d’un pouvoir immense et maléfique. Il permet à son détenteur de se rendre invisible et lui confère une autorité sans limites sur les possesseurs des autres anneaux. Bref, il fait de lui le Maître du Monde. C’est pourquoi Sauron s’est juré de reconquérir l’anneau par tous les moyens. Déjà ses Cavaliers Noirs rôdent aux frontières de la Comté. '},
    {imgSrc: require('../components/Images/Livres/EpeeShannara.png'),
    title:'L’EPEE DE SHANNARA',
    date:'2002',
     serieLivre:'Shannara',
      genreLivre:'Fantasy',
       auteurLivre:'Terry Brooks',
        nombrePageLivre:'400',
         editeurLivre:'Bragelonne',
          isbnLivre:'2-914370-31-8',
           resumeLivre:'\nLorsque Shea Ohmsford vit pénétrer l’étranger dans l’auberge, il sentit que son destin venait de basculer. Qui aurait pu deviner qu’il était, lui le paisible demi-elfe vivant au sein de sa famille d’adoption à Valombre, le dernier héritier de la lignée de Jerle Shannara ? Jerle, dont l’épée permit, il y a cinq cents de cela, de détruire le maléfique Roi-Sorcier Brona et ses hordes démoniaques. Or voilà qu’il se murmure, dans les lointaines Terres du Nord, que le Roi-Sorcier est de retour et qu’il réunit ses armées pour déferler à nouveau sur le monde. Seul un descendant de Jerle, portant la légendaire Epée de Shannara, pourrait défaire le mal. Shea acceptera-t-il cet oracle trop grand pour lui ? '},
    {imgSrc: require('../components/Images/Livres/HarryPotter.png'),
    title:'HARRY POTTER A L’ECOLE DES SORCIERS',
    date:'1998',
     serieLivre:'HARRY POTTER',
      genreLivre:'Fantasy',
       auteurLivre:'J. K. Rowling',
        nombrePageLivre:'308',
         editeurLivre:'Gallimard Jeunesse',
          isbnLivre:'\n2-07-051842-6',
           resumeLivre:'Après la mort de ses parents (Lily et James Potter), Harry Potter est recueilli par sa tante maternelle Pétunia et son oncle Vernon à l’âge d un an. Ces derniers, animés depuis toujours d’une haine féroce envers les parents du garçon qu’ils qualifient de gens « bizarres », voire de « monstres », traitent froidement leur neveu et demeurent indifférents aux humiliations que leur fils Dudley lui fait subir. Harry ignore tout de l’histoire de ses parents, si ce n’est qu ils ont été, semble-t-il, tués dans un accident de voiture. Cependant, le jour des onze ans de Harry, un demi-géant du nom de Rubeus Hagrid vient le chercher pour l’informer de son inscription à Poudlard, une école de sorcellerie où il est inscrit depuis sa naissance et lui remettre sa lettre...'},
    {imgSrc: require('../components/Images/Livres/LaBeteHumaine.png'),
    title:'LA BETE HUMAINE',
    date:'1889',
     serieLivre:'Les Rougon-Macquart',
      genreLivre:'Roman naturaliste',
       auteurLivre:'Émile Zola',
        nombrePageLivre:'412',
         editeurLivre:'G. Charpentier',
          isbnLivre:' - ',
           resumeLivre:'\nFils de Gervaise Macquart et d’Auguste Lantier, Lantier est employé sur une ligne ferroviaire. Il est passionné par son travail et tente de s’y vouer totalement, car il craint en lui les pulsions meurtrières qui l’agitent. Elles seraient dues au lourd héritage alcoolique de sa famille. 2. Roubaud Roubaud est également un employé des chemins de fer. Il est le protégé du président de la compagnie : Grandmorin. Roubaud est un personnage qui va complètement se transformer au cours du roman : il va évoluer de mari aimant et employé modèle à un homme assassin, alcoolique et maltraitant sa femme. '},
    {imgSrc: require('../components/Images/Livres/LaMemoireDansLaPeau.png'),
    title:'La mémoire dans la peau',
    date:'1981',
     serieLivre:'Jason Bourne',
      genreLivre:'Espionnage',
       auteurLivre:'Robert Ludlum',
        nombrePageLivre:'465',
         editeurLivre:'Robert Laffont',
          isbnLivre:'978-2221007020',
           resumeLivre:'\nUn homme est retrouvé grièvement blessé au large de Marseille. Soigné par un médecin, il se révèle amnésique, mais son corps montre des traces de chirurgie esthétique. Il décide de découvrir son identité en partant des indications trouvées dans un micro-film implanté sous sa peau. Bourne découvre peu à peu ses talents : il connaît plusieurs langues étrangères, sait se battre et possède une grande capacité à se travestir et assumer des rôles.\nÀ Zurich, il se rend dans une banque où il a accès à un compte en banque très bien fourni. Poursuivi par de mystérieux tueurs à la solde de Carlos, un tueur à gages mondialement réputé, il rencontre la femme qui deviendra sa complice et son amante, une experte canadienne en finances internationales nommée Marie Saint-Jacques. Ensemble, ils fuient pour Paris, où Bourne croit qu’il trouvera une réponse à sa quête...'},
    {imgSrc: require('../components/Images/Livres/LaNuitDesTemps.png'),
    title:'La nuit des temps',
    date:'1968',
    serieLivre:' - ',
     genreLivre:'Science-fiction',
      auteurLivre:'René Barjavel',
       nombrePageLivre:'317',
        editeurLivre:'Presses de la Cité',
         isbnLivre:' - ',
          resumeLivre:'\nEn plein Antarctique, une mission scientifique française capte un signal inattendu qui provient des profondeurs glacées. Il s’agit d’un émetteur placé là 900 000 ans auparavant. Plusieurs nations qui fraternisent dans l adversité des rudes conditions polaires entreprennent alors des fouilles passionnées. Une sphère est mise au jour dans laquelle deux individus reposent en hibernation : un homme et une femme, tous deux masqués. La femme, réanimée en premier, se nomme Eléa. Elle est d’une beauté exceptionnelle. Un ingénieux système - « la Traductrice » - lui permet d’expliquer la guerre totale qui a conduit un savant de son époque, Coban, à l’enfermer avec lui dans cet abri. Mais la jeune femme explique qu’elle aurait préféré mourir aux côtés de celui qu elle aime d un amour sans nom : Païkan. En apprenant qu elle a dormi 900 000 ans, elle fait une dépression...'},
    {imgSrc: require('../components/Images/Livres/LEpreuve.png'),
    title:'LE LABYRINTHE',
    date:'2012',
     serieLivre:'L ÉPREUVE',
      genreLivre:'Science-fiction',
       auteurLivre:'James Dashner',
        nombrePageLivre:'404',
         editeurLivre:'Pocket Jeunesse',
          isbnLivre:'978-2266200127',
           resumeLivre:'\nQuand Thomas reprend connaissance, sa mémoire est vide, seul son nom lui est familier... Il se retrouve entouré d adolescents dans un lieu étrange, à l’ombre de murs infranchissables. Quatre portes gigantesques, qui se referment le soir, ouvrent sur un labyrinthe peuplé de monstres d’acier. Chaque nuit, le plan du labyrinthe en est modifié.\nThomas comprend qu’une terrible épreuve les attend tous. Comment s’échapper par le labyrinthe maudit sans risquer sa vie et celle de ses camarades ? Si seulement il parvenait à exhumer les sombres secrets enfouis au plus profond de sa mémoire... '},
    {imgSrc: require('../components/Images/Livres/RendezVousRama.png'),
    title:'Rendez-vous avec Rama',
    date:'1975',
     serieLivre:'RAMA',
      genreLivre:'Science-fiction',
       auteurLivre:'Arthur C. Clarke',
        nombrePageLivre:'304',
         editeurLivre:'Robert Laffont',
          isbnLivre:'0-575-01587-X',
           resumeLivre:'\nEn 2130, les radars terrestres repèrent un gigantesque cylindre qui pénètre dans le Système solaire. D abord identifié comme l astéroïde 31/439, on lui attribue le nom Rama en hommage au prince hindou Rama (« les astronomes [ayant] depuis longtemps épuisé la mythologie grecque et romaine3 »), quand on réalise que son envergure de 50 km de long par 20 km de diamètre et sa perfection impliquent nécessairement une origine extraterrestre.\nL équipe du vaisseau Endeavour, en mission de routine avant la découverte, est chargée d aller à la rencontre du vaisseau, qui a déjà atteint l orbite de Vénus, pour l explorer. Ils réalisent progressivement que le cylindre, qui à première vue semblait inhabité, est occupé par de bien étranges créatures...'}
]
export {books}

/**
 * Les données
 * imgSrc : page de garde du livre
 * title : titre du livre
 * date : date de parution française du livre
 * serieLivre : indique si le livre fait parti d'un ensemble
 * genreLivre : genre du livre
 * auteurLivre : nom ou nom de plume de l'auteur du livre
 * nombrePageLivre : nombre de pages du livre
 * editeurLivre : editeur du livre dans sa version française (si le livre en a plusieurs suivant les versions on n'en prends qu'un)
 * isbnLivre : ISBN du livre s'il existe
 * resumeLivre : Résumé ou descriptif du livre
 */